version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'  
    restart: unless-stopped  
    ports: ["2181:2181"]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    restart: unless-stopped
    ports: ["9092:9092"]
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: "2"
    depends_on:
      - zookeeper
    

