version: "3.8"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181

  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      #KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - 9092:9092

  producer:
    build:
      context: ./services/producer/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 3000:3000

  miembros:
    build:
      context: ./services/Miembros/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - producer
    ports:
      - 8000:3000

  ventas:
    build:
      context: ./services/Ventas/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - producer
    ports:
      - 8001:3000

  ubicaciones:
    build:
      context: ./services/Ubicaciones/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - producer
    ports:
      - 8002:3000 
  stock:
    build:
      context: ./services/Stock/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - producer
    ports:
      - 8003:3000     